### ISSUE TITLE
transfer repo's ownership?

### ISSUE THREAD

**Issue by cecileane** [nstenz/hybseq#2]
Hi Noah, 
Would you mind transferring ownership of this repo? Nisa is still struggling to make it work, and we would like to help, but it would be best if one of us (Corrinne @iamcorrinne or me) could own the repo to have one central repo (instead of one fork serving as the central repo).
Let me know. Thanks!

**Comment by nstenz** [comment]
Hi Cecile,

I tried to transfer the repository to you but I got an error because you
already had a repo named hybseq. I've now transfered it to Corrinne as you
suggested.

Hope you're well,
Noah

**Comment by cecileane** [comment]
Perfect. Many thanks Noah! (my hybseq was a fork of yours; github is quick at creating these forks).
All is well here :)
